---
class: 4
flags: 0x0000
unid: OF826AE81BC15714C1-ON0055FE8888258805
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: WEB-INF/faces-config.xml
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
    signed: true
  - name: $TITLE
    type: text
    data: WEB-INF/faces-config.xml
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []