---
class: 4
flags: 0x0000
unid: OF179941029C0C7270-ON0007E64888258816
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $Flags
    type: text
    data: D34CiQ
  - name: $FlagsExt
    type: text
    data: D
    signed: true
  - name: $ImageNames
    type: text
    data: ApplicationIcon-Thumbnail.png
    signed: true
  - name: $ImagesColorize
    type: number
    data: 0
    signed: true
  - name: $ImagesHigh
    type: number
    data: 1
    signed: true
  - name: $ImagesWide
    type: number
    data: 1
    signed: true
  - name: $MimeType
    type: text
    data: image/png
    signed: true
  - name: $TITLE
    type: text
    data: Thumbnail-ApplicationIcon.png
    signed: true
  - name: $ImageData
    type: composite
    signed: true
    nonsummary: true
remaining: []