---
ACL:
  opaque: |
    Q0ECAEoBBQAAAAAABQAoABAAeACYAAAAAAAoAAQAAAAEBCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAACIBAAAAAAAABAEAAAAAAAAAANwAAAAAAAAAAAAAAEVBAgAAAAAAAAAAAAAAAAAJAC1EZWZhdWx0
    LQAAAEVBBgAAAAAAAAAAAAAA+AcRAExvY2FsRG9tYWluQWRtaW5zALYARUEGAAAAAAAAAAAAAADaBxIA
    TG9jYWxEb21haW5TZXJ2ZXJzAEEAAEVBAAAAAAAAAAAAAAAABBAJAEFub255bW91cwAAAEVBAAAAAAAA
    AAAAAAAARhASAE90aGVyRG9tYWluU2VydmVycwBt
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0