---
ACL:
  opaque: |
    Q0ECAA4HBQAAAAAABQDsBRAAPAZcBgAAAAAoAAQAAAAEBCgAuAUUADEyLzExLzIwMjMgMDQ6MTM6MzUg
    UE0gRGF2ZSBDb2hlbi9VU0EvUE5QSENMIGFkZGVkIE90aGVyRG9tYWluU2VydmVycwAxMi8xMS8yMDIz
    IDA0OjEzOjM1IFBNIERhdmUgQ29oZW4vVVNBL1BOUEhDTCBkZWxldGVkIFtbT3RoZXJEb21haW5TZXJ2
    ZXJzXV0AMTIvMTEvMjAyMyAwNDoxMzozNSBQTSBEYXZlIENvaGVuL1VTQS9QTlBIQ0wgZGVsZXRlZCBb
    Wy1EZWZhdWx0LV1dADEyLzExLzIwMjMgMDQ6MTM6MzUgUE0gRGF2ZSBDb2hlbi9VU0EvUE5QSENMIGFk
    ZGVkIEFub255bW91cwAxMi8xMS8yMDIzIDA0OjEzOjM1IFBNIERhdmUgQ29oZW4vVVNBL1BOUEhDTCBk
    ZWxldGVkIFtbQW5vbnltb3VzXV0AMTIvMTEvMjAyMyAwNDoxMzozNSBQTSBEYXZlIENvaGVuL1VTQS9Q
    TlBIQ0wgYWRkZWQgTG9jYWxEb21haW5TZXJ2ZXJzADEyLzExLzIwMjMgMDQ6MTM6MzUgUE0gRGF2ZSBD
    b2hlbi9VU0EvUE5QSENMIGRlbGV0ZWQgW1tMb2NhbERvbWFpblNlcnZlcnNdXQAxMi8xMS8yMDIzIDA0
    OjEzOjM1IFBNIERhdmUgQ29oZW4vVVNBL1BOUEhDTCBhZGRlZCBMb2NhbERvbWFpbkFkbWlucwAxMi8x
    MS8yMDIzIDA0OjEzOjM1IFBNIERhdmUgQ29oZW4vVVNBL1BOUEhDTCBkZWxldGVkIFtbTG9jYWxEb21h
    aW5BZG1pbnNdXQAxMi8xMS8yMDIzIDA0OjEzOjM1IFBNIERhdmUgQ29oZW4vVVNBL1BOUEhDTCBkZWxl
    dGVkIE5hdGFsaWUgTWV6emluYS9VU0EvUE5QSENMADEyLzExLzIwMjMgMDQ6MTM6MzUgUE0gRGF2ZSBD
    b2hlbi9VU0EvUE5QSENMIGRlbGV0ZWQgU2NvdHQgTydLZWVmZS9VU0EvUE5QSENMADEyLzExLzIwMjMg
    MDQ6MTM6MzUgUE0gRGF2ZSBDb2hlbi9VU0EvUE5QSENMIGRlbGV0ZWQgTG9jYWxEb21haW5BZG1pbnMA
    MTIvMTEvMjAyMyAwNDoxMzozNSBQTSBEYXZlIENvaGVuL1VTQS9QTlBIQ0wgZGVsZXRlZCBTY290dCBW
    cnVzaG8vVVNBL1BOUEhDTAAxMi8xMS8yMDIzIDA0OjEzOjM1IFBNIERhdmUgQ29oZW4vVVNBL1BOUEhD
    TCBkZWxldGVkIEJyaWFuIEFybm9sZC9VU0EvUE5QSENMADEyLzExLzIwMjMgMDQ6MTM6MzUgUE0gRGF2
    ZSBDb2hlbi9VU0EvUE5QSENMIGRlbGV0ZWQgTWFzdGVya2V5L1NlcnZlci9UZW1wbGF0ZXMAMTIvMTEv
    MjAyMyAwNDoxMzozNSBQTSBEYXZlIENvaGVuL1VTQS9QTlBIQ0wgZGVsZXRlZCBNYXN0ZXJsb2NrL1Nl
    cnZlci9UZW1wbGF0ZXMAMTIvMTEvMjAyMyAwNDoxMzozNSBQTSBEYXZlIENvaGVuL1VTQS9QTlBIQ0wg
    ZGVsZXRlZCBNYXJ5IEUgTWlsbGVyL1VTQS9QTlBIQ0wAMTIvMTEvMjAyMyAwNDoxMzozNSBQTSBEYXZl
    IENvaGVuL1VTQS9QTlBIQ0wgZGVsZXRlZCBBbm9ueW1vdXMAMTIvMTEvMjAyMyAwNDoxMzozNSBQTSBE
    YXZlIENvaGVuL1VTQS9QTlBIQ0wgdXBkYXRlZCBNYXN0ZXJsb2NrL1NlcnZlci9UZW1wbGF0ZXMAMTIv
    MTEvMjAyMyAwNDoxMjo0OCBQTSBEYXZlIENvaGVuL1VTQS9QTlBIQ0wgdXBkYXRlZCBbWy1EZWZhdWx0
    LV1dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOYGAAAAAAAAyAYAAAAAAAAAAKAG
    AAAAAAAAAAAAAEVBAgAAAAAAAAAAAAAAAAAJAC1EZWZhdWx0LQAAAEVBBgAAAAAAAAAAAAAA+AcRAExv
    Y2FsRG9tYWluQWRtaW5zAHoGRUEGAAAAAAAAAAAAAADaBxIATG9jYWxEb21haW5TZXJ2ZXJzAEEAAEVB
    AAAAAAAAAAAAAAAABBAJAEFub255bW91cwAAAEVBAAAAAAAAAAAAAAAARhASAE90aGVyRG9tYWluU2Vy
    dmVycwBt
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0